# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x07isegram\"\x0e\n\x0cPostsRequest\"\x1a\n\nPostsReply\x12\x0c\n\x04name\x18\x01 \x03(\t2J\n\x0cPostsService\x12:\n\nGetProduct\x12\x15.isegram.PostsRequest\x1a\x13.isegram.PostsReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTSREQUEST']._serialized_start=23
  _globals['_POSTSREQUEST']._serialized_end=37
  _globals['_POSTSREPLY']._serialized_start=39
  _globals['_POSTSREPLY']._serialized_end=65
  _globals['_POSTSSERVICE']._serialized_start=67
  _globals['_POSTSSERVICE']._serialized_end=141
# @@protoc_insertion_point(module_scope)
